import { createRoot } from 'react-dom/client';
import App from './app/index';

// Add div to bare HTML generated by HtmlWebpackPlugin
const rootDiv = document.createElement('div');
rootDiv.id = 'root';
document.body.appendChild(rootDiv);

const container = document.getElementById('root');
const root = createRoot(container!);
root.render(<App />);
